---
- name: 'Instalar dependências do do Mysql'
  apt:
    name: [
      'mysql-server-5.6',
      'python-mysqldb',
    ]
    state: latest
  become: yes

- name: 'Instalar Mysql'
  mysql_db:
    name: "{{ wp_db_name }}"
    login_user: root
    state: present

- name: 'Adicionando usuário no bd'
  mysql_user:
    login_user: root
    name: "{{ wp_username }}"
    password: '{{wp_user_password}}'
    priv: '{{ wp_db_name }}.*:ALL'
    state: present
    host: '{{ item }}'
  with_items:
    - "{{wp_host_ip}}"
    
- name: 'Configurar arquivo para aceitar conexões remotas.'
  copy:
    src: 'files/my.cnf'
    dest: '/etc/mysql/my.cnf'
  become: yes
  notify:
    - restart mysql